apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortio
  namespace: cinemaabyss
  labels:
    app: fortio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fortio
  template:
    metadata:
      labels:
        app: fortio
    spec:
      containers:
        - name: fortio
          image: fortio/fortio:latest
          args: ["server"]
          ports:
            - containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: fortio
  namespace: cinemaabyss
spec:
  selector:
    app: fortio
  ports:
    - name: http
      port: 8090
      targetPort: 8090
  type: ClusterIP
